# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_auto_20161005_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='organization',
            name='end_date',
            field=models.CharField(blank=True, help_text='The date when the validity of the item ends', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date has wrong format', regex='^[0-9]{4}(-[0-9]{2}){0,2}$'), organization.models.validate_partial_date], verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='start_date',
            field=models.CharField(blank=True, help_text='The date when the validity of the item starts', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date has wrong format', regex='^[0-9]{4}(-[0-9]{2}){0,2}$'), organization.models.validate_partial_date], verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time'),
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='end_date',
            field=models.CharField(blank=True, help_text='The date when the validity of the item ends', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date has wrong format', regex='^[0-9]{4}(-[0-9]{2}){0,2}$'), organization.models.validate_partial_date], verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='start_date',
            field=models.CharField(blank=True, help_text='The date when the validity of the item starts', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date has wrong format', regex='^[0-9]{4}(-[0-9]{2}){0,2}$'), organization.models.validate_partial_date], verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time'),
        ),
    ]
