# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_auto_20161005_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='nature_of_work',
            new_name='data_processing_description',
        ),
        migrations.RenameField(
            model_name='organizationdraft',
            old_name='nature_of_work',
            new_name='data_processing_description',
        ),
    ]
