# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_identifier_link_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='area',
            name='parent',
        ),
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.CharField(blank=True, default='United Kingdom', help_text='Jurisdiction that organisation is registered in', max_length=1024, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='organizationdraft',
            name='area',
            field=models.CharField(blank=True, default='United Kingdom', help_text='Jurisdiction that organisation is registered in', max_length=1024, verbose_name='area'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
