# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0040_auto_20161005_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('classification', models.CharField(help_text='A classification for this Organization within some classification scheme', max_length=512, verbose_name='classification')),
                ('scheme', models.CharField(blank=True, help_text='A classification scheme, e.g. SIC', max_length=128, verbose_name='scheme')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='organizationdraft',
            name='classification',
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.CharField(blank=True, help_text="Tags that reflect e.g. the organization's type", max_length=512, verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='tags',
            field=models.CharField(blank=True, help_text="Tags that reflect e.g. the organization's type", max_length=512, verbose_name='tags'),
        ),
    ]
