services:
  - postgresql
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - cd getyourdata
  - chmod +x create_dev_db.bash
  - sudo ./create_dev_db.bash
install:
  - cd getyourdata
  - pip install -r requirements.txt
  - python manage.py migrate
# command to run tests
script: python manage.py test
