services:
  - postgresql
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - cd getyourdata
  - sudo ./create_dev_db.bash
install:
  - pip install -r requirements.txt
  - python dev_manage.py migrate
# command to run tests
script: python dev_manage.py test
